name: Build
on:
  push:
    branches:
      - main

concurrency:
  group: build-${{github.ref}}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: buckhamduffy/release-drafter@v1
        id: version
        with:
          master_branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-chrome:
    name: Build Chrome
    runs-on: ubuntu-latest
    needs: [release]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ needs.release.outputs.version }}

      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - run: echo "VERSION=${{ needs.release.outputs.version }}" > .env.production

      - name: Build Chrome
        run: bun run build-chrome

      - name: Upload Chrome Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          cd dist
          zip -r chrome.zip *
          cd ../
          gh release upload ${{ needs.release.outputs.version }} ./dist/chrome.zip

  build-firefox:
    name: Build Firefox
    runs-on: ubuntu-latest
    needs: [ release ]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ needs.release.outputs.version }}

      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - run: echo "VERSION=${{ needs.release.outputs.version }}" > .env.production

      - name: Build Firefox
        run: bun run build-firefox

      - name: web-ext Bundle
        id: web-ext-build
        uses: kewisch/action-web-ext@v1
        with:
          cmd: build
          source: dist
          filename: "bd-fake-filler-${{ needs.release.outputs.version }}.xpi"

      - name: Create source code zip
        run: git archive --format=zip --output=sources.zip ${{ needs.release.outputs.version }}

      - name: web-ext sign AMO
        id: web-ext-sign
        uses: kewisch/action-web-ext@v1
        with:
          cmd: sign
          source: ${{ steps.web-ext-build.outputs.target }}
          sourceCode: sources.zip
          channel: unlisted
          approvalNotes: "Please find more information at https://github.com/buckhamduffy/fake-filler-extension"
          apiKey: ${{ secrets.AMO_SIGN_KEY }}
          apiSecret: ${{ secrets.AMO_SIGN_SECRET }}
          timeout: 900000
          license: MIT

      - name: Attach release assets to release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          mv ${{ steps.web-ext-sign.outputs.target }} web-ext-artifacts/firefox.xpi
          mv ${{ steps.web-ext-build.outputs.target }} web-ext-artifacts/firefox-unsigned.xpi
          gh release upload ${{ needs.release.outputs.version }} web-ext-artifacts/firefox.xpi web-ext-artifacts/firefox-unsigned.xpi
