name: Build
on:
  push:
    branches:
      - main

concurrency:
  group: build-${{github.ref}}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: buckhamduffy/release-drafter@v1
        id: version
        with:
          master_branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [release]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ needs.release.outputs.version }}

      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - run: echo "VERSION=${{ needs.release.outputs.version }}" > .env.production

      - name: Build Chrome
        run: bun run build-chrome

      - name: Upload Chrome Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          cd dist
          zip -r chrome.zip *
          cd ../
          gh release upload ${{ needs.release.outputs.version }} chrome.zip

      - name: Build Firefox
        run: bun run build-firefox

      - name: Upload Firefox Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          cd dist
          zip -r firefox.zip *
          cd ../
          gh release upload ${{ needs.release.outputs.version }} firefox.zip

